app = "cold-smoke-3829"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[mounts]
  source = "cold_smoke_3829"
  destination = "/app/db"
  initial_size = 1

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "60s"
    path = "/health"
    method = "get"
    protocol = "http"
    interval = "30s"
    timeout = "5s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
