name: Deploy

on:
  push:
    branches: [ flyio ]

jobs:
#  checks:
#    uses: ./.github/workflows/checks.yaml
#
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: "flyctl"

      - name: Build and deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy
